version: "3.5"

services:
  mongo_homelike:
    image: mongo:latest
    container_name: mongo_homelike
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "0.0.0.0:${MONGO_DB_PORT}:27017"
    networks:
      - MONGO
    volumes:
      - type: volume
        source: HOMELIKE_DB
        target: /data/db
  mongo_express_homelike:
    image: mongo-express:latest
    container_name: mongo_express_homelike
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongo_homelike'
    ports:
      - "0.0.0.0:${MONGO_EXPRESS_PORT}:8081"
    networks:
      - MONGO
    depends_on:
      - mongo_homelike
networks:
  MONGO:
    name: MONGO

volumes:
  HOMELIKE_DB:
    name: HOMELIKE_DB
